### ISSUE TITLE
Error with user which is no created in the database

### ISSUE THREAD

**Issue by kevincaradant** [CedricGatay/docker-koel#2]
Hi again Cedric,

I try twice to run your docker with php on debian8.1 image ( i all delete and rebuild to be sure ), but i have always the same error .

![image](https://cloud.githubusercontent.com/assets/6093175/11920269/66ea8b2a-a76a-11e5-9108-b9daa038d372.png)

In fact, in the database i see the account 'root' with the password 'bowbeforeme' but there are not the user 'db' . Why ? What's missing ?

![image](https://cloud.githubusercontent.com/assets/6093175/11920325/1e66f58a-a76c-11e5-89fc-a4773097bab1.png)

Merci d'avance :)

**Comment by CedricGatay** [comment]
Strange behavior, I've rebuilt from scratch and everything looks ok. The user is supposed to be root (not db). Have you changed the env file ?

AFAIK it does not matter we're connecting as root, as the db is only used for this app ;).

`docker-compose kill; docker-compose rm -f; docker-compose build;` and start again with `docker-compose up -d db; sleep 60; docker-compose up -d app;` it should be ok.

Regards,

**Comment by kevincaradant** [comment]
hoho maybe it's me i didn't understand why in the docker-compose file , there is 'db' and in env file there is 'root'. I think i edited at the begin , i totally forgot this ... , i said you if it's good :) , why two names differents by the way ? 

Edit : ok ... now i have that [PDOException]  
  SQLSTATE[HY000] [2003] Can't connect to MySQL server on 'db' (113) . I just edit .env file in the docker image and put 'root' insteed of 'db' and reset the artisan server but i get this error. I try again to reinstall all you think , it's so long with my computer ^.^ but i don't think it's very usefull :/ , if you see the problem i listen you , in the other case i erase all and let run during 30 min.

OK i rebuild all like that i will be sure, so  i will told you if it's good :)

**Comment by CedricGatay** [comment]
It is still a work in progress. I need to refine it ;)

**Comment by kevincaradant** [comment]
It's good , thank you :). I'm thought, when you write the environment var for the docker-compose like mysql_user = "db" in the docker-compose file, that will go to create the user "db" in the same time that he pulled the image but i'm surprised because he creates the database "db" when i check into the image. So why not the user ? maybe i missed something or not understand ...

I'm sorry to ask again one question but since yesterday , i get this error : 

```
Recreating koooooo_db_1...
Recreating koooooo_app_1...
Cannot start container 4e43fca8d6a3f427bde42cea3251fb5e2297a823da81fa08356a6d69fb37e723: [8] System error: permission denied
```

and i didin't find a fix for that , do you already have this error ? i get this with image from Ubuntu ... thank you :)
